/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AccessControlRight = {
    View: 'view',
    Edit: 'edit'
} as const;
export type AccessControlRight =
        | 'view' 
        | 'edit' 
;


export function AccessControlRightFromJSON(json: any): AccessControlRight {
    return AccessControlRightFromJSONTyped(json, false);
}

export function AccessControlRightFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessControlRight {
    return json as AccessControlRight;
}

export function AccessControlRightToJSON(value?: AccessControlRight | null): any {
    return value as any;
}

