/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const AccessControlRight = {
    view: 'view',
    edit: 'edit'
} as const;
export type AccessControlRight =
        | 'view' 
        | 'edit' 
;


export function instanceOfAccessControlRight(value: unknown): boolean {
    return (Object.values(AccessControlRight) as unknown[]).includes(value);
}

export function AccessControlRightFromJSON(json: unknown): AccessControlRight {
    return AccessControlRightFromJSONTyped(json, false);
}

export function AccessControlRightFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): AccessControlRight {
    return json as AccessControlRight;
}

export function AccessControlRightToJSON(value?: AccessControlRight | null): AccessControlRight | null | undefined {
    return value;
}

