/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const AnalyticRight = {
    view: 'view'
} as const;
export type AnalyticRight =
        | 'view' 
;


export function instanceOfAnalyticRight(value: unknown): boolean {
    return (Object.values(AnalyticRight) as unknown[]).includes(value);
}

export function AnalyticRightFromJSON(json: unknown): AnalyticRight {
    return AnalyticRightFromJSONTyped(json, false);
}

export function AnalyticRightFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): AnalyticRight {
    return json as AnalyticRight;
}

export function AnalyticRightToJSON(value?: AnalyticRight | null): AnalyticRight | null | undefined {
    return value;
}

