/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AnalyticRight = {
    View: 'view'
} as const;
export type AnalyticRight =
        | 'view' 
;


export function AnalyticRightFromJSON(json: any): AnalyticRight {
    return AnalyticRightFromJSONTyped(json, false);
}

export function AnalyticRightFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticRight {
    return json as AnalyticRight;
}

export function AnalyticRightToJSON(value?: AnalyticRight | null): any {
    return value as any;
}

