/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CacheObject } from './CacheObject';
import {
    CacheObjectFromJSON,
    CacheObjectFromJSONTyped,
    CacheObjectToJSON,
} from './CacheObject';

/**
 * 
 * @export
 * @interface CacheObjectResponse
 */
export interface CacheObjectResponse {
    /**
     * 
     * @type {CacheObject}
     * @memberof CacheObjectResponse
     */
    cacheObject: CacheObject;
    /**
     * 
     * @type {string}
     * @memberof CacheObjectResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof CacheObjectResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the CacheObjectResponse interface.
 */
export function instanceOfCacheObjectResponse(value: object): value is CacheObjectResponse {
    if (!('cacheObject' in value) || value['cacheObject'] === undefined) return false;
    return true;
}

export function CacheObjectResponseFromJSON(json: any): CacheObjectResponse {
    return CacheObjectResponseFromJSONTyped(json, false);
}

export function CacheObjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheObjectResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'cacheObject': CacheObjectFromJSON(json['cacheObject']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function CacheObjectResponseToJSON(value?: CacheObjectResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'cacheObject': CacheObjectToJSON(value['cacheObject']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

