/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CacheKeysResponse
 */
export interface CacheKeysResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof CacheKeysResponse
     */
    cacheKeys: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CacheKeysResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof CacheKeysResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the CacheKeysResponse interface.
 */
export function instanceOfCacheKeysResponse(value: object): value is CacheKeysResponse {
    if (!('cacheKeys' in value) || value['cacheKeys'] === undefined) return false;
    return true;
}

export function CacheKeysResponseFromJSON(json: any): CacheKeysResponse {
    return CacheKeysResponseFromJSONTyped(json, false);
}

export function CacheKeysResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheKeysResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'cacheKeys': json['cacheKeys'],
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function CacheKeysResponseToJSON(value?: CacheKeysResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'cacheKeys': value['cacheKeys'],
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

