/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CacheObject
 */
export interface CacheObject {
    /**
     * 
     * @type {number}
     * @memberof CacheObject
     */
    createdAt: number;
    /**
     * 
     * @type {number}
     * @memberof CacheObject
     */
    expireTimestamp?: number;
    /**
     * 
     * @type {number}
     * @memberof CacheObject
     */
    lastReadAt?: number;
    /**
     * 
     * @type {string}
     * @memberof CacheObject
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof CacheObject
     */
    value: string;
}

/**
 * Check if a given object implements the CacheObject interface.
 */
export function instanceOfCacheObject(value: object): value is CacheObject {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function CacheObjectFromJSON(json: any): CacheObject {
    return CacheObjectFromJSONTyped(json, false);
}

export function CacheObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): CacheObject {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'],
        'expireTimestamp': json['expireTimestamp'] == null ? undefined : json['expireTimestamp'],
        'lastReadAt': json['lastReadAt'] == null ? undefined : json['lastReadAt'],
        'key': json['key'],
        'value': json['value'],
    };
}

export function CacheObjectToJSON(value?: CacheObject | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createdAt': value['createdAt'],
        'expireTimestamp': value['expireTimestamp'],
        'lastReadAt': value['lastReadAt'],
        'key': value['key'],
        'value': value['value'],
    };
}

