/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ExerciseRight = {
    Edit: 'edit'
} as const;
export type ExerciseRight =
        | 'edit' 
;


export function ExerciseRightFromJSON(json: any): ExerciseRight {
    return ExerciseRightFromJSONTyped(json, false);
}

export function ExerciseRightFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseRight {
    return json as ExerciseRight;
}

export function ExerciseRightToJSON(value?: ExerciseRight | null): any {
    return value as any;
}

