/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const ExerciseRight = {
    edit: 'edit'
} as const;
export type ExerciseRight =
        | 'edit' 
;


export function instanceOfExerciseRight(value: unknown): boolean {
    return (Object.values(ExerciseRight) as unknown[]).includes(value);
}

export function ExerciseRightFromJSON(json: unknown): ExerciseRight {
    return ExerciseRightFromJSONTyped(json, false);
}

export function ExerciseRightFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): ExerciseRight {
    return json as ExerciseRight;
}

export function ExerciseRightToJSON(value?: ExerciseRight | null): ExerciseRight | null | undefined {
    return value;
}

