/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const FacilityRight = {
    view: 'view',
    edit: 'edit'
} as const;
export type FacilityRight =
        | 'view' 
        | 'edit' 
;


export function instanceOfFacilityRight(value: unknown): boolean {
    return (Object.values(FacilityRight) as unknown[]).includes(value);
}

export function FacilityRightFromJSON(json: unknown): FacilityRight {
    return FacilityRightFromJSONTyped(json, false);
}

export function FacilityRightFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): FacilityRight {
    return json as FacilityRight;
}

export function FacilityRightToJSON(value?: FacilityRight | null): FacilityRight | null | undefined {
    return value;
}

