/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.3.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FacilityRight = {
    View: 'view',
    Edit: 'edit'
} as const;
export type FacilityRight =
        | 'view' 
        | 'edit' 
;


export function FacilityRightFromJSON(json: any): FacilityRight {
    return FacilityRightFromJSONTyped(json, false);
}

export function FacilityRightFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacilityRight {
    return json as FacilityRight;
}

export function FacilityRightToJSON(value?: FacilityRight | null): any {
    return value as any;
}

