/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRight } from './UserRight';
import {
    UserRightFromJSON,
    UserRightFromJSONTyped,
    UserRightToJSON,
} from './UserRight';
import type { UserData } from './UserData';
import {
    UserDataFromJSON,
    UserDataFromJSONTyped,
    UserDataToJSON,
} from './UserData';
import type { AccessControlRight } from './AccessControlRight';
import {
    AccessControlRightFromJSON,
    AccessControlRightFromJSONTyped,
    AccessControlRightToJSON,
} from './AccessControlRight';
import type { ExerciseRight } from './ExerciseRight';
import {
    ExerciseRightFromJSON,
    ExerciseRightFromJSONTyped,
    ExerciseRightToJSON,
} from './ExerciseRight';
import type { LicenseRight } from './LicenseRight';
import {
    LicenseRightFromJSON,
    LicenseRightFromJSONTyped,
    LicenseRightToJSON,
} from './LicenseRight';
import type { FacilityRight } from './FacilityRight';
import {
    FacilityRightFromJSON,
    FacilityRightFromJSONTyped,
    FacilityRightToJSON,
} from './FacilityRight';
import type { MSeriesGuidedSessionRight } from './MSeriesGuidedSessionRight';
import {
    MSeriesGuidedSessionRightFromJSON,
    MSeriesGuidedSessionRightFromJSONTyped,
    MSeriesGuidedSessionRightToJSON,
} from './MSeriesGuidedSessionRight';
import type { AnalyticRight } from './AnalyticRight';
import {
    AnalyticRightFromJSON,
    AnalyticRightFromJSONTyped,
    AnalyticRightToJSON,
} from './AnalyticRight';
import type { ResqueRight } from './ResqueRight';
import {
    ResqueRightFromJSON,
    ResqueRightFromJSONTyped,
    ResqueRightToJSON,
} from './ResqueRight';

/**
 * 
 * @export
 * @interface GlobalAccessControlData
 */
export interface GlobalAccessControlData {
    /**
     * 
     * @type {number}
     * @memberof GlobalAccessControlData
     */
    userId: number;
    /**
     * 
     * @type {UserRight}
     * @memberof GlobalAccessControlData
     */
    userRights?: UserRight;
    /**
     * 
     * @type {ExerciseRight}
     * @memberof GlobalAccessControlData
     */
    exerciseRights?: ExerciseRight;
    /**
     * 
     * @type {MSeriesGuidedSessionRight}
     * @memberof GlobalAccessControlData
     */
    mSeriesGuidedSessionRights?: MSeriesGuidedSessionRight;
    /**
     * 
     * @type {FacilityRight}
     * @memberof GlobalAccessControlData
     */
    facilityRights?: FacilityRight;
    /**
     * 
     * @type {LicenseRight}
     * @memberof GlobalAccessControlData
     */
    licenseRights?: LicenseRight;
    /**
     * 
     * @type {AccessControlRight}
     * @memberof GlobalAccessControlData
     */
    accessControlRights?: AccessControlRight;
    /**
     * 
     * @type {ResqueRight}
     * @memberof GlobalAccessControlData
     */
    resqueRights?: ResqueRight;
    /**
     * 
     * @type {AnalyticRight}
     * @memberof GlobalAccessControlData
     */
    analyticRights?: AnalyticRight;
    /**
     * 
     * @type {UserData}
     * @memberof GlobalAccessControlData
     */
    user?: UserData;
}

/**
 * Check if a given object implements the GlobalAccessControlData interface.
 */
export function instanceOfGlobalAccessControlData(value: object): value is GlobalAccessControlData {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function GlobalAccessControlDataFromJSON(json: any): GlobalAccessControlData {
    return GlobalAccessControlDataFromJSONTyped(json, false);
}

export function GlobalAccessControlDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalAccessControlData {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'userRights': json['userRights'] == null ? undefined : UserRightFromJSON(json['userRights']),
        'exerciseRights': json['exerciseRights'] == null ? undefined : ExerciseRightFromJSON(json['exerciseRights']),
        'mSeriesGuidedSessionRights': json['mSeriesGuidedSessionRights'] == null ? undefined : MSeriesGuidedSessionRightFromJSON(json['mSeriesGuidedSessionRights']),
        'facilityRights': json['facilityRights'] == null ? undefined : FacilityRightFromJSON(json['facilityRights']),
        'licenseRights': json['licenseRights'] == null ? undefined : LicenseRightFromJSON(json['licenseRights']),
        'accessControlRights': json['accessControlRights'] == null ? undefined : AccessControlRightFromJSON(json['accessControlRights']),
        'resqueRights': json['resqueRights'] == null ? undefined : ResqueRightFromJSON(json['resqueRights']),
        'analyticRights': json['analyticRights'] == null ? undefined : AnalyticRightFromJSON(json['analyticRights']),
        'user': json['user'] == null ? undefined : UserDataFromJSON(json['user']),
    };
}

export function GlobalAccessControlDataToJSON(value?: GlobalAccessControlData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'userRights': UserRightToJSON(value['userRights']),
        'exerciseRights': ExerciseRightToJSON(value['exerciseRights']),
        'mSeriesGuidedSessionRights': MSeriesGuidedSessionRightToJSON(value['mSeriesGuidedSessionRights']),
        'facilityRights': FacilityRightToJSON(value['facilityRights']),
        'licenseRights': LicenseRightToJSON(value['licenseRights']),
        'accessControlRights': AccessControlRightToJSON(value['accessControlRights']),
        'resqueRights': ResqueRightToJSON(value['resqueRights']),
        'analyticRights': AnalyticRightToJSON(value['analyticRights']),
        'user': UserDataToJSON(value['user']),
    };
}

