/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GlobalAccessControlData } from './GlobalAccessControlData';
import {
    GlobalAccessControlDataFromJSON,
    GlobalAccessControlDataFromJSONTyped,
    GlobalAccessControlDataToJSON,
} from './GlobalAccessControlData';
import type { GlobalAccessControlSecretData } from './GlobalAccessControlSecretData';
import {
    GlobalAccessControlSecretDataFromJSON,
    GlobalAccessControlSecretDataFromJSONTyped,
    GlobalAccessControlSecretDataToJSON,
} from './GlobalAccessControlSecretData';

/**
 * 
 * @export
 * @interface GlobalAccessControlCreationResponse
 */
export interface GlobalAccessControlCreationResponse {
    /**
     * 
     * @type {GlobalAccessControlData}
     * @memberof GlobalAccessControlCreationResponse
     */
    globalAccessControl: GlobalAccessControlData;
    /**
     * 
     * @type {GlobalAccessControlSecretData}
     * @memberof GlobalAccessControlCreationResponse
     */
    globalAccessControlSecret: GlobalAccessControlSecretData;
    /**
     * 
     * @type {string}
     * @memberof GlobalAccessControlCreationResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalAccessControlCreationResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the GlobalAccessControlCreationResponse interface.
 */
export function instanceOfGlobalAccessControlCreationResponse(value: object): value is GlobalAccessControlCreationResponse {
    if (!('globalAccessControl' in value) || value['globalAccessControl'] === undefined) return false;
    if (!('globalAccessControlSecret' in value) || value['globalAccessControlSecret'] === undefined) return false;
    return true;
}

export function GlobalAccessControlCreationResponseFromJSON(json: any): GlobalAccessControlCreationResponse {
    return GlobalAccessControlCreationResponseFromJSONTyped(json, false);
}

export function GlobalAccessControlCreationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalAccessControlCreationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'globalAccessControl': GlobalAccessControlDataFromJSON(json['globalAccessControl']),
        'globalAccessControlSecret': GlobalAccessControlSecretDataFromJSON(json['globalAccessControlSecret']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function GlobalAccessControlCreationResponseToJSON(value?: GlobalAccessControlCreationResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'globalAccessControl': GlobalAccessControlDataToJSON(value['globalAccessControl']),
        'globalAccessControlSecret': GlobalAccessControlSecretDataToJSON(value['globalAccessControlSecret']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

