/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GlobalAccessControlSecretData } from './GlobalAccessControlSecretData';
import {
    GlobalAccessControlSecretDataFromJSON,
    GlobalAccessControlSecretDataFromJSONTyped,
    GlobalAccessControlSecretDataToJSON,
} from './GlobalAccessControlSecretData';

/**
 * 
 * @export
 * @interface GlobalAccessControlSecretResponse
 */
export interface GlobalAccessControlSecretResponse {
    /**
     * 
     * @type {GlobalAccessControlSecretData}
     * @memberof GlobalAccessControlSecretResponse
     */
    globalAccessControlSecret: GlobalAccessControlSecretData;
    /**
     * 
     * @type {string}
     * @memberof GlobalAccessControlSecretResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof GlobalAccessControlSecretResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the GlobalAccessControlSecretResponse interface.
 */
export function instanceOfGlobalAccessControlSecretResponse(value: object): value is GlobalAccessControlSecretResponse {
    if (!('globalAccessControlSecret' in value) || value['globalAccessControlSecret'] === undefined) return false;
    return true;
}

export function GlobalAccessControlSecretResponseFromJSON(json: any): GlobalAccessControlSecretResponse {
    return GlobalAccessControlSecretResponseFromJSONTyped(json, false);
}

export function GlobalAccessControlSecretResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalAccessControlSecretResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'globalAccessControlSecret': GlobalAccessControlSecretDataFromJSON(json['globalAccessControlSecret']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function GlobalAccessControlSecretResponseToJSON(value?: GlobalAccessControlSecretResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'globalAccessControlSecret': GlobalAccessControlSecretDataToJSON(value['globalAccessControlSecret']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

