/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GlobalAccessControlSorting } from './GlobalAccessControlSorting';
import {
    GlobalAccessControlSortingFromJSON,
    GlobalAccessControlSortingFromJSONTyped,
    GlobalAccessControlSortingToJSON,
} from './GlobalAccessControlSorting';

/**
 * 
 * @export
 * @interface GlobalAccessControlListResponseMeta
 */
export interface GlobalAccessControlListResponseMeta {
    /**
     * 
     * @type {string}
     * @memberof GlobalAccessControlListResponseMeta
     */
    name?: string;
    /**
     * 
     * @type {GlobalAccessControlSorting}
     * @memberof GlobalAccessControlListResponseMeta
     */
    sort: GlobalAccessControlSorting;
    /**
     * 
     * @type {boolean}
     * @memberof GlobalAccessControlListResponseMeta
     */
    ascending?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GlobalAccessControlListResponseMeta
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof GlobalAccessControlListResponseMeta
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof GlobalAccessControlListResponseMeta
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the GlobalAccessControlListResponseMeta interface.
 */
export function instanceOfGlobalAccessControlListResponseMeta(value: object): value is GlobalAccessControlListResponseMeta {
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function GlobalAccessControlListResponseMetaFromJSON(json: any): GlobalAccessControlListResponseMeta {
    return GlobalAccessControlListResponseMetaFromJSONTyped(json, false);
}

export function GlobalAccessControlListResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalAccessControlListResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'sort': GlobalAccessControlSortingFromJSON(json['sort']),
        'ascending': json['ascending'] == null ? undefined : json['ascending'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function GlobalAccessControlListResponseMetaToJSON(value?: GlobalAccessControlListResponseMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'sort': GlobalAccessControlSortingToJSON(value['sort']),
        'ascending': value['ascending'],
        'limit': value['limit'],
        'offset': value['offset'],
        'totalCount': value['totalCount'],
    };
}

