/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.3.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccessControlRight } from './AccessControlRight';
import {
    AccessControlRightFromJSON,
    AccessControlRightFromJSONTyped,
    AccessControlRightToJSON,
} from './AccessControlRight';
import type { AnalyticRight } from './AnalyticRight';
import {
    AnalyticRightFromJSON,
    AnalyticRightFromJSONTyped,
    AnalyticRightToJSON,
} from './AnalyticRight';
import type { ExerciseRight } from './ExerciseRight';
import {
    ExerciseRightFromJSON,
    ExerciseRightFromJSONTyped,
    ExerciseRightToJSON,
} from './ExerciseRight';
import type { FacilityRight } from './FacilityRight';
import {
    FacilityRightFromJSON,
    FacilityRightFromJSONTyped,
    FacilityRightToJSON,
} from './FacilityRight';
import type { LicenseRight } from './LicenseRight';
import {
    LicenseRightFromJSON,
    LicenseRightFromJSONTyped,
    LicenseRightToJSON,
} from './LicenseRight';
import type { MSeriesGuidedSessionRight } from './MSeriesGuidedSessionRight';
import {
    MSeriesGuidedSessionRightFromJSON,
    MSeriesGuidedSessionRightFromJSONTyped,
    MSeriesGuidedSessionRightToJSON,
} from './MSeriesGuidedSessionRight';
import type { ResqueRight } from './ResqueRight';
import {
    ResqueRightFromJSON,
    ResqueRightFromJSONTyped,
    ResqueRightToJSON,
} from './ResqueRight';
import type { UserData } from './UserData';
import {
    UserDataFromJSON,
    UserDataFromJSONTyped,
    UserDataToJSON,
} from './UserData';
import type { UserRight } from './UserRight';
import {
    UserRightFromJSON,
    UserRightFromJSONTyped,
    UserRightToJSON,
} from './UserRight';

/**
 * 
 * @export
 * @interface GlobalAccessControlData
 */
export interface GlobalAccessControlData {
    /**
     * 
     * @type {number}
     * @memberof GlobalAccessControlData
     */
    userId: number;
    /**
     * 
     * @type {UserRight}
     * @memberof GlobalAccessControlData
     */
    userRights?: UserRight;
    /**
     * 
     * @type {ExerciseRight}
     * @memberof GlobalAccessControlData
     */
    exerciseRights?: ExerciseRight;
    /**
     * 
     * @type {MSeriesGuidedSessionRight}
     * @memberof GlobalAccessControlData
     */
    mSeriesGuidedSessionRights?: MSeriesGuidedSessionRight;
    /**
     * 
     * @type {FacilityRight}
     * @memberof GlobalAccessControlData
     */
    facilityRights?: FacilityRight;
    /**
     * 
     * @type {LicenseRight}
     * @memberof GlobalAccessControlData
     */
    licenseRights?: LicenseRight;
    /**
     * 
     * @type {AccessControlRight}
     * @memberof GlobalAccessControlData
     */
    accessControlRights?: AccessControlRight;
    /**
     * 
     * @type {ResqueRight}
     * @memberof GlobalAccessControlData
     */
    resqueRights?: ResqueRight;
    /**
     * 
     * @type {AnalyticRight}
     * @memberof GlobalAccessControlData
     */
    analyticRights?: AnalyticRight;
    /**
     * 
     * @type {UserData}
     * @memberof GlobalAccessControlData
     */
    user?: UserData;
}

/**
 * Check if a given object implements the GlobalAccessControlData interface.
 */
export function instanceOfGlobalAccessControlData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function GlobalAccessControlDataFromJSON(json: any): GlobalAccessControlData {
    return GlobalAccessControlDataFromJSONTyped(json, false);
}

export function GlobalAccessControlDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalAccessControlData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'userRights': !exists(json, 'userRights') ? undefined : UserRightFromJSON(json['userRights']),
        'exerciseRights': !exists(json, 'exerciseRights') ? undefined : ExerciseRightFromJSON(json['exerciseRights']),
        'mSeriesGuidedSessionRights': !exists(json, 'mSeriesGuidedSessionRights') ? undefined : MSeriesGuidedSessionRightFromJSON(json['mSeriesGuidedSessionRights']),
        'facilityRights': !exists(json, 'facilityRights') ? undefined : FacilityRightFromJSON(json['facilityRights']),
        'licenseRights': !exists(json, 'licenseRights') ? undefined : LicenseRightFromJSON(json['licenseRights']),
        'accessControlRights': !exists(json, 'accessControlRights') ? undefined : AccessControlRightFromJSON(json['accessControlRights']),
        'resqueRights': !exists(json, 'resqueRights') ? undefined : ResqueRightFromJSON(json['resqueRights']),
        'analyticRights': !exists(json, 'analyticRights') ? undefined : AnalyticRightFromJSON(json['analyticRights']),
        'user': !exists(json, 'user') ? undefined : UserDataFromJSON(json['user']),
    };
}

export function GlobalAccessControlDataToJSON(value?: GlobalAccessControlData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'userRights': UserRightToJSON(value.userRights),
        'exerciseRights': ExerciseRightToJSON(value.exerciseRights),
        'mSeriesGuidedSessionRights': MSeriesGuidedSessionRightToJSON(value.mSeriesGuidedSessionRights),
        'facilityRights': FacilityRightToJSON(value.facilityRights),
        'licenseRights': LicenseRightToJSON(value.licenseRights),
        'accessControlRights': AccessControlRightToJSON(value.accessControlRights),
        'resqueRights': ResqueRightToJSON(value.resqueRights),
        'analyticRights': AnalyticRightToJSON(value.analyticRights),
        'user': UserDataToJSON(value.user),
    };
}

