/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const GlobalAccessControlSorting = {
    id: 'id',
    name: 'name'
} as const;
export type GlobalAccessControlSorting =
        | 'id' 
        | 'name' 
;


export function instanceOfGlobalAccessControlSorting(value: unknown): boolean {
    return (Object.values(GlobalAccessControlSorting) as unknown[]).includes(value);
}

export function GlobalAccessControlSortingFromJSON(json: unknown): GlobalAccessControlSorting {
    return GlobalAccessControlSortingFromJSONTyped(json, false);
}

export function GlobalAccessControlSortingFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): GlobalAccessControlSorting {
    return json as GlobalAccessControlSorting;
}

export function GlobalAccessControlSortingToJSON(value?: GlobalAccessControlSorting | null): GlobalAccessControlSorting | null | undefined {
    return value;
}

