/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.0.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface High
 */
export interface High {
    /**
     * 
     * @type {number}
     * @memberof High
     */
    length: number;
}

/**
 * Check if a given object implements the High interface.
 */
export function instanceOfHigh(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "length" in value;

    return isInstance;
}

export function HighFromJSON(json: any): High {
    return HighFromJSONTyped(json, false);
}

export function HighFromJSONTyped(json: any, ignoreDiscriminator: boolean): High {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'length': json['length'],
    };
}

export function HighToJSON(value?: High | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'length': value.length,
    };
}

