/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface High
 */
export interface High {
    /**
     * 
     * @type {number}
     * @memberof High
     */
    length: number;
}

/**
 * Check if a given object implements the High interface.
 */
export function instanceOfHigh(value: object): value is High {
    if (!('length' in value) || value['length'] === undefined) return false;
    return true;
}

export function HighFromJSON(json: any): High {
    return HighFromJSONTyped(json, false);
}

export function HighFromJSONTyped(json: any, ignoreDiscriminator: boolean): High {
    if (json == null) {
        return json;
    }
    return {
        
        'length': json['length'],
    };
}

export function HighToJSON(value?: High | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'length': value['length'],
    };
}

