/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.3.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LicenseRight = {
    View: 'view',
    Edit: 'edit'
} as const;
export type LicenseRight =
        | 'view' 
        | 'edit' 
;


export function LicenseRightFromJSON(json: any): LicenseRight {
    return LicenseRightFromJSONTyped(json, false);
}

export function LicenseRightFromJSONTyped(json: any, ignoreDiscriminator: boolean): LicenseRight {
    return json as LicenseRight;
}

export function LicenseRightToJSON(value?: LicenseRight | null): any {
    return value as any;
}

