/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const LicenseRight = {
    view: 'view',
    edit: 'edit'
} as const;
export type LicenseRight =
        | 'view' 
        | 'edit' 
;


export function instanceOfLicenseRight(value: unknown): boolean {
    return (Object.values(LicenseRight) as unknown[]).includes(value);
}

export function LicenseRightFromJSON(json: unknown): LicenseRight {
    return LicenseRightFromJSONTyped(json, false);
}

export function LicenseRightFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): LicenseRight {
    return json as LicenseRight;
}

export function LicenseRightToJSON(value?: LicenseRight | null): LicenseRight | null | undefined {
    return value;
}

