/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MSeriesGuidedSessionRight = {
    Access: 'access',
    Publish: 'publish'
} as const;
export type MSeriesGuidedSessionRight =
        | 'access' 
        | 'publish' 
;


export function MSeriesGuidedSessionRightFromJSON(json: any): MSeriesGuidedSessionRight {
    return MSeriesGuidedSessionRightFromJSONTyped(json, false);
}

export function MSeriesGuidedSessionRightFromJSONTyped(json: any, ignoreDiscriminator: boolean): MSeriesGuidedSessionRight {
    return json as MSeriesGuidedSessionRight;
}

export function MSeriesGuidedSessionRightToJSON(value?: MSeriesGuidedSessionRight | null): any {
    return value as any;
}

