/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const MSeriesGuidedSessionRight = {
    access: 'access',
    publish: 'publish'
} as const;
export type MSeriesGuidedSessionRight =
        | 'access' 
        | 'publish' 
;


export function instanceOfMSeriesGuidedSessionRight(value: unknown): boolean {
    return (Object.values(MSeriesGuidedSessionRight) as unknown[]).includes(value);
}

export function MSeriesGuidedSessionRightFromJSON(json: unknown): MSeriesGuidedSessionRight {
    return MSeriesGuidedSessionRightFromJSONTyped(json, false);
}

export function MSeriesGuidedSessionRightFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): MSeriesGuidedSessionRight {
    return json as MSeriesGuidedSessionRight;
}

export function MSeriesGuidedSessionRightToJSON(value?: MSeriesGuidedSessionRight | null): MSeriesGuidedSessionRight | null | undefined {
    return value;
}

