/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const Queue = {
    high: 'high',
    low: 'low'
} as const;
export type Queue =
        | 'high' 
        | 'low' 
;


export function instanceOfQueue(value: unknown): boolean {
    return (Object.values(Queue) as unknown[]).includes(value);
}

export function QueueFromJSON(json: unknown): Queue {
    return QueueFromJSONTyped(json, false);
}

export function QueueFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): Queue {
    return json as Queue;
}

export function QueueToJSON(value?: Queue | null): Queue | null | undefined {
    return value;
}

