/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskQueues } from './TaskQueues';
import {
    TaskQueuesFromJSON,
    TaskQueuesFromJSONTyped,
    TaskQueuesToJSON,
} from './TaskQueues';
import type { TaskStats } from './TaskStats';
import {
    TaskStatsFromJSON,
    TaskStatsFromJSONTyped,
    TaskStatsToJSON,
} from './TaskStats';

/**
 * 
 * @export
 * @interface ResqueDetailsData
 */
export interface ResqueDetailsData {
    /**
     * 
     * @type {TaskQueues}
     * @memberof ResqueDetailsData
     */
    queues: TaskQueues;
    /**
     * 
     * @type {TaskStats}
     * @memberof ResqueDetailsData
     */
    stats: TaskStats;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ResqueDetailsData
     */
    workers: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof ResqueDetailsData
     */
    leader: string;
}

/**
 * Check if a given object implements the ResqueDetailsData interface.
 */
export function instanceOfResqueDetailsData(value: object): value is ResqueDetailsData {
    if (!('queues' in value) || value['queues'] === undefined) return false;
    if (!('stats' in value) || value['stats'] === undefined) return false;
    if (!('workers' in value) || value['workers'] === undefined) return false;
    if (!('leader' in value) || value['leader'] === undefined) return false;
    return true;
}

export function ResqueDetailsDataFromJSON(json: any): ResqueDetailsData {
    return ResqueDetailsDataFromJSONTyped(json, false);
}

export function ResqueDetailsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResqueDetailsData {
    if (json == null) {
        return json;
    }
    return {
        
        'queues': TaskQueuesFromJSON(json['queues']),
        'stats': TaskStatsFromJSON(json['stats']),
        'workers': json['workers'],
        'leader': json['leader'],
    };
}

export function ResqueDetailsDataToJSON(value?: ResqueDetailsData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'queues': TaskQueuesToJSON(value['queues']),
        'stats': TaskStatsToJSON(value['stats']),
        'workers': value['workers'],
        'leader': value['leader'],
    };
}

