/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const ResqueRight = {
    view: 'view',
    edit: 'edit'
} as const;
export type ResqueRight =
        | 'view' 
        | 'edit' 
;


export function instanceOfResqueRight(value: unknown): boolean {
    return (Object.values(ResqueRight) as unknown[]).includes(value);
}

export function ResqueRightFromJSON(json: unknown): ResqueRight {
    return ResqueRightFromJSONTyped(json, false);
}

export function ResqueRightFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): ResqueRight {
    return json as ResqueRight;
}

export function ResqueRightToJSON(value?: ResqueRight | null): ResqueRight | null | undefined {
    return value;
}

