/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ResqueRight = {
    View: 'view',
    Edit: 'edit'
} as const;
export type ResqueRight =
        | 'view' 
        | 'edit' 
;


export function ResqueRightFromJSON(json: any): ResqueRight {
    return ResqueRightFromJSONTyped(json, false);
}

export function ResqueRightFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResqueRight {
    return json as ResqueRight;
}

export function ResqueRightToJSON(value?: ResqueRight | null): any {
    return value as any;
}

