/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatSorting } from './StatSorting';
import {
    StatSortingFromJSON,
    StatSortingFromJSONTyped,
    StatSortingToJSON,
} from './StatSorting';

/**
 * 
 * @export
 * @interface StatListResponseMeta
 */
export interface StatListResponseMeta {
    /**
     * 
     * @type {Date}
     * @memberof StatListResponseMeta
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof StatListResponseMeta
     */
    to?: Date;
    /**
     * 
     * @type {StatSorting}
     * @memberof StatListResponseMeta
     */
    sort: StatSorting;
    /**
     * 
     * @type {boolean}
     * @memberof StatListResponseMeta
     */
    ascending?: boolean;
    /**
     * 
     * @type {number}
     * @memberof StatListResponseMeta
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof StatListResponseMeta
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof StatListResponseMeta
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the StatListResponseMeta interface.
 */
export function instanceOfStatListResponseMeta(value: object): value is StatListResponseMeta {
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function StatListResponseMetaFromJSON(json: any): StatListResponseMeta {
    return StatListResponseMetaFromJSONTyped(json, false);
}

export function StatListResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatListResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'] == null ? undefined : (new Date(json['from'])),
        'to': json['to'] == null ? undefined : (new Date(json['to'])),
        'sort': StatSortingFromJSON(json['sort']),
        'ascending': json['ascending'] == null ? undefined : json['ascending'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function StatListResponseMetaToJSON(value?: StatListResponseMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'from': value['from'] == null ? undefined : ((value['from']).toISOString()),
        'to': value['to'] == null ? undefined : ((value['to']).toISOString()),
        'sort': StatSortingToJSON(value['sort']),
        'ascending': value['ascending'],
        'limit': value['limit'],
        'offset': value['offset'],
        'totalCount': value['totalCount'],
    };
}

