/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatData
 */
export interface StatData {
    /**
     * 
     * @type {number}
     * @memberof StatData
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof StatData
     */
    createdAt: string;
    /**
     * 
     * @type {number}
     * @memberof StatData
     */
    users: number;
    /**
     * 
     * @type {number}
     * @memberof StatData
     */
    msApps: number;
    /**
     * 
     * @type {number}
     * @memberof StatData
     */
    sessions: number;
    /**
     * 
     * @type {number}
     * @memberof StatData
     */
    oauths: number;
    /**
     * 
     * @type {number}
     * @memberof StatData
     */
    facebook: number;
    /**
     * 
     * @type {number}
     * @memberof StatData
     */
    google: number;
    /**
     * 
     * @type {number}
     * @memberof StatData
     */
    apple: number;
    /**
     * 
     * @type {number}
     * @memberof StatData
     */
    trainingpeaks: number;
    /**
     * 
     * @type {number}
     * @memberof StatData
     */
    strava: number;
    /**
     * 
     * @type {number}
     * @memberof StatData
     */
    inbody: number;
}

/**
 * Check if a given object implements the StatData interface.
 */
export function instanceOfStatData(value: object): value is StatData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('users' in value) || value['users'] === undefined) return false;
    if (!('msApps' in value) || value['msApps'] === undefined) return false;
    if (!('sessions' in value) || value['sessions'] === undefined) return false;
    if (!('oauths' in value) || value['oauths'] === undefined) return false;
    if (!('facebook' in value) || value['facebook'] === undefined) return false;
    if (!('google' in value) || value['google'] === undefined) return false;
    if (!('apple' in value) || value['apple'] === undefined) return false;
    if (!('trainingpeaks' in value) || value['trainingpeaks'] === undefined) return false;
    if (!('strava' in value) || value['strava'] === undefined) return false;
    if (!('inbody' in value) || value['inbody'] === undefined) return false;
    return true;
}

export function StatDataFromJSON(json: any): StatData {
    return StatDataFromJSONTyped(json, false);
}

export function StatDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': json['createdAt'],
        'users': json['users'],
        'msApps': json['msApps'],
        'sessions': json['sessions'],
        'oauths': json['oauths'],
        'facebook': json['facebook'],
        'google': json['google'],
        'apple': json['apple'],
        'trainingpeaks': json['trainingpeaks'],
        'strava': json['strava'],
        'inbody': json['inbody'],
    };
}

export function StatDataToJSON(value?: StatData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'createdAt': value['createdAt'],
        'users': value['users'],
        'msApps': value['msApps'],
        'sessions': value['sessions'],
        'oauths': value['oauths'],
        'facebook': value['facebook'],
        'google': value['google'],
        'apple': value['apple'],
        'trainingpeaks': value['trainingpeaks'],
        'strava': value['strava'],
        'inbody': value['inbody'],
    };
}

