/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const StatSorting = {
    id: 'id',
    createdAt: 'createdAt'
} as const;
export type StatSorting =
        | 'id' 
        | 'createdAt' 
;


export function instanceOfStatSorting(value: unknown): boolean {
    return (Object.values(StatSorting) as unknown[]).includes(value);
}

export function StatSortingFromJSON(json: unknown): StatSorting {
    return StatSortingFromJSONTyped(json, false);
}

export function StatSortingFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): StatSorting {
    return json as StatSorting;
}

export function StatSortingToJSON(value?: StatSorting | null): StatSorting | null | undefined {
    return value;
}

