/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatListResponseMeta } from './StatListResponseMeta';
import {
    StatListResponseMetaFromJSON,
    StatListResponseMetaFromJSONTyped,
    StatListResponseMetaToJSON,
} from './StatListResponseMeta';
import type { StatData } from './StatData';
import {
    StatDataFromJSON,
    StatDataFromJSONTyped,
    StatDataToJSON,
} from './StatData';

/**
 * 
 * @export
 * @interface StatListResponse
 */
export interface StatListResponse {
    /**
     * 
     * @type {Array<StatData>}
     * @memberof StatListResponse
     */
    stats: Array<StatData>;
    /**
     * 
     * @type {StatListResponseMeta}
     * @memberof StatListResponse
     */
    statsMeta: StatListResponseMeta;
    /**
     * 
     * @type {string}
     * @memberof StatListResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof StatListResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the StatListResponse interface.
 */
export function instanceOfStatListResponse(value: object): value is StatListResponse {
    if (!('stats' in value) || value['stats'] === undefined) return false;
    if (!('statsMeta' in value) || value['statsMeta'] === undefined) return false;
    return true;
}

export function StatListResponseFromJSON(json: any): StatListResponse {
    return StatListResponseFromJSONTyped(json, false);
}

export function StatListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'stats': ((json['stats'] as Array<any>).map(StatDataFromJSON)),
        'statsMeta': StatListResponseMetaFromJSON(json['statsMeta']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function StatListResponseToJSON(value?: StatListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'stats': ((value['stats'] as Array<any>).map(StatDataToJSON)),
        'statsMeta': StatListResponseMetaToJSON(value['statsMeta']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

