/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskQueueResponseMeta } from './TaskQueueResponseMeta';
import {
    TaskQueueResponseMetaFromJSON,
    TaskQueueResponseMetaFromJSONTyped,
    TaskQueueResponseMetaToJSON,
} from './TaskQueueResponseMeta';
import type { TaskPayload } from './TaskPayload';
import {
    TaskPayloadFromJSON,
    TaskPayloadFromJSONTyped,
    TaskPayloadToJSON,
} from './TaskPayload';

/**
 * 
 * @export
 * @interface TaskQueueResponse
 */
export interface TaskQueueResponse {
    /**
     * 
     * @type {Array<TaskPayload>}
     * @memberof TaskQueueResponse
     */
    tasks: Array<TaskPayload>;
    /**
     * 
     * @type {TaskQueueResponseMeta}
     * @memberof TaskQueueResponse
     */
    tasksMeta: TaskQueueResponseMeta;
    /**
     * 
     * @type {string}
     * @memberof TaskQueueResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskQueueResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the TaskQueueResponse interface.
 */
export function instanceOfTaskQueueResponse(value: object): value is TaskQueueResponse {
    if (!('tasks' in value) || value['tasks'] === undefined) return false;
    if (!('tasksMeta' in value) || value['tasksMeta'] === undefined) return false;
    return true;
}

export function TaskQueueResponseFromJSON(json: any): TaskQueueResponse {
    return TaskQueueResponseFromJSONTyped(json, false);
}

export function TaskQueueResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskQueueResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tasks': ((json['tasks'] as Array<any>).map(TaskPayloadFromJSON)),
        'tasksMeta': TaskQueueResponseMetaFromJSON(json['tasksMeta']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function TaskQueueResponseToJSON(value?: TaskQueueResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tasks': ((value['tasks'] as Array<any>).map(TaskPayloadToJSON)),
        'tasksMeta': TaskQueueResponseMetaToJSON(value['tasksMeta']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

