/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskSorting } from './TaskSorting';
import {
    TaskSortingFromJSON,
    TaskSortingFromJSONTyped,
    TaskSortingToJSON,
} from './TaskSorting';

/**
 * 
 * @export
 * @interface TaskQueueResponseMeta
 */
export interface TaskQueueResponseMeta {
    /**
     * 
     * @type {string}
     * @memberof TaskQueueResponseMeta
     */
    queue: string;
    /**
     * 
     * @type {TaskSorting}
     * @memberof TaskQueueResponseMeta
     */
    sort: TaskSorting;
    /**
     * 
     * @type {boolean}
     * @memberof TaskQueueResponseMeta
     */
    ascending?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TaskQueueResponseMeta
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskQueueResponseMeta
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskQueueResponseMeta
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the TaskQueueResponseMeta interface.
 */
export function instanceOfTaskQueueResponseMeta(value: object): value is TaskQueueResponseMeta {
    if (!('queue' in value) || value['queue'] === undefined) return false;
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function TaskQueueResponseMetaFromJSON(json: any): TaskQueueResponseMeta {
    return TaskQueueResponseMetaFromJSONTyped(json, false);
}

export function TaskQueueResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskQueueResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'queue': json['queue'],
        'sort': TaskSortingFromJSON(json['sort']),
        'ascending': json['ascending'] == null ? undefined : json['ascending'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function TaskQueueResponseMetaToJSON(value?: TaskQueueResponseMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'queue': value['queue'],
        'sort': TaskSortingToJSON(value['sort']),
        'ascending': value['ascending'],
        'limit': value['limit'],
        'offset': value['offset'],
        'totalCount': value['totalCount'],
    };
}

