/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskStats
 */
export interface TaskStats {
    /**
     * 
     * @type {string}
     * @memberof TaskStats
     */
    failed?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskStats
     */
    processed?: string;
}

/**
 * Check if a given object implements the TaskStats interface.
 */
export function instanceOfTaskStats(value: object): value is TaskStats {
    return true;
}

export function TaskStatsFromJSON(json: any): TaskStats {
    return TaskStatsFromJSONTyped(json, false);
}

export function TaskStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskStats {
    if (json == null) {
        return json;
    }
    return {
        
        'failed': json['failed'] == null ? undefined : json['failed'],
        'processed': json['processed'] == null ? undefined : json['processed'],
    };
}

export function TaskStatsToJSON(value?: TaskStats | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'failed': value['failed'],
        'processed': value['processed'],
    };
}

