/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskPayload } from './TaskPayload';
import {
    TaskPayloadFromJSON,
    TaskPayloadFromJSONTyped,
    TaskPayloadToJSON,
} from './TaskPayload';
import type { Queue } from './Queue';
import {
    QueueFromJSON,
    QueueFromJSONTyped,
    QueueToJSON,
} from './Queue';

/**
 * 
 * @export
 * @interface TaskFailure
 */
export interface TaskFailure {
    /**
     * 
     * @type {Array<string>}
     * @memberof TaskFailure
     */
    backtrace: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TaskFailure
     */
    error: string;
    /**
     * 
     * @type {string}
     * @memberof TaskFailure
     */
    exception: string;
    /**
     * 
     * @type {string}
     * @memberof TaskFailure
     */
    failedAt: string;
    /**
     * 
     * @type {TaskPayload}
     * @memberof TaskFailure
     */
    payload: TaskPayload;
    /**
     * 
     * @type {Queue}
     * @memberof TaskFailure
     */
    queue: Queue;
    /**
     * 
     * @type {string}
     * @memberof TaskFailure
     */
    worker: string;
}

/**
 * Check if a given object implements the TaskFailure interface.
 */
export function instanceOfTaskFailure(value: object): value is TaskFailure {
    if (!('backtrace' in value) || value['backtrace'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('exception' in value) || value['exception'] === undefined) return false;
    if (!('failedAt' in value) || value['failedAt'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('queue' in value) || value['queue'] === undefined) return false;
    if (!('worker' in value) || value['worker'] === undefined) return false;
    return true;
}

export function TaskFailureFromJSON(json: any): TaskFailure {
    return TaskFailureFromJSONTyped(json, false);
}

export function TaskFailureFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskFailure {
    if (json == null) {
        return json;
    }
    return {
        
        'backtrace': json['backtrace'],
        'error': json['error'],
        'exception': json['exception'],
        'failedAt': json['failed_at'],
        'payload': TaskPayloadFromJSON(json['payload']),
        'queue': QueueFromJSON(json['queue']),
        'worker': json['worker'],
    };
}

export function TaskFailureToJSON(value?: TaskFailure | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'backtrace': value['backtrace'],
        'error': value['error'],
        'exception': value['exception'],
        'failed_at': value['failedAt'],
        'payload': TaskPayloadToJSON(value['payload']),
        'queue': QueueToJSON(value['queue']),
        'worker': value['worker'],
    };
}

