/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const TaskSorting = {
    id: 'id'
} as const;
export type TaskSorting =
        | 'id' 
;


export function instanceOfTaskSorting(value: unknown): boolean {
    return (Object.values(TaskSorting) as unknown[]).includes(value);
}

export function TaskSortingFromJSON(json: unknown): TaskSorting {
    return TaskSortingFromJSONTyped(json, false);
}

export function TaskSortingFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): TaskSorting {
    return json as TaskSorting;
}

export function TaskSortingToJSON(value?: TaskSorting | null): TaskSorting | null | undefined {
    return value;
}

