/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskQueueResponseMeta } from './TaskQueueResponseMeta';
import {
    TaskQueueResponseMetaFromJSON,
    TaskQueueResponseMetaFromJSONTyped,
    TaskQueueResponseMetaToJSON,
} from './TaskQueueResponseMeta';
import type { TaskFailure } from './TaskFailure';
import {
    TaskFailureFromJSON,
    TaskFailureFromJSONTyped,
    TaskFailureToJSON,
} from './TaskFailure';

/**
 * 
 * @export
 * @interface TaskFailedResponse
 */
export interface TaskFailedResponse {
    /**
     * 
     * @type {Array<TaskFailure>}
     * @memberof TaskFailedResponse
     */
    tasks: Array<TaskFailure>;
    /**
     * 
     * @type {TaskQueueResponseMeta}
     * @memberof TaskFailedResponse
     */
    tasksMeta: TaskQueueResponseMeta;
    /**
     * 
     * @type {string}
     * @memberof TaskFailedResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof TaskFailedResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the TaskFailedResponse interface.
 */
export function instanceOfTaskFailedResponse(value: object): value is TaskFailedResponse {
    if (!('tasks' in value) || value['tasks'] === undefined) return false;
    if (!('tasksMeta' in value) || value['tasksMeta'] === undefined) return false;
    return true;
}

export function TaskFailedResponseFromJSON(json: any): TaskFailedResponse {
    return TaskFailedResponseFromJSONTyped(json, false);
}

export function TaskFailedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskFailedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tasks': ((json['tasks'] as Array<any>).map(TaskFailureFromJSON)),
        'tasksMeta': TaskQueueResponseMetaFromJSON(json['tasksMeta']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function TaskFailedResponseToJSON(value?: TaskFailedResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tasks': ((value['tasks'] as Array<any>).map(TaskFailureToJSON)),
        'tasksMeta': TaskQueueResponseMetaToJSON(value['tasksMeta']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

