/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.3.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UserRight = {
    View: 'view',
    Edit: 'edit'
} as const;
export type UserRight =
        | 'view' 
        | 'edit' 
;


export function UserRightFromJSON(json: any): UserRight {
    return UserRightFromJSONTyped(json, false);
}

export function UserRightFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRight {
    return json as UserRight;
}

export function UserRightToJSON(value?: UserRight | null): any {
    return value as any;
}

