/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const UserRight = {
    view: 'view',
    edit: 'edit'
} as const;
export type UserRight =
        | 'view' 
        | 'edit' 
;


export function instanceOfUserRight(value: unknown): boolean {
    return (Object.values(UserRight) as unknown[]).includes(value);
}

export function UserRightFromJSON(json: unknown): UserRight {
    return UserRightFromJSONTyped(json, false);
}

export function UserRightFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): UserRight {
    return json as UserRight;
}

export function UserRightToJSON(value?: UserRight | null): UserRight | null | undefined {
    return value;
}

