/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 */
export const UserSorting = {
    id: 'id',
    name: 'name',
    createdAt: 'createdAt'
} as const;
export type UserSorting =
        | 'id' 
        | 'name' 
        | 'createdAt' 
;


export function instanceOfUserSorting(value: unknown): boolean {
    return (Object.values(UserSorting) as unknown[]).includes(value);
}

export function UserSortingFromJSON(json: unknown): UserSorting {
    return UserSortingFromJSONTyped(json, false);
}

export function UserSortingFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): UserSorting {
    return json as UserSorting;
}

export function UserSortingToJSON(value?: UserSorting | null): UserSorting | null | undefined {
    return value;
}

