/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserData } from './UserData';
import {
    UserDataFromJSON,
    UserDataFromJSONTyped,
    UserDataToJSON,
} from './UserData';
import type { UserListResponseMeta } from './UserListResponseMeta';
import {
    UserListResponseMetaFromJSON,
    UserListResponseMetaFromJSONTyped,
    UserListResponseMetaToJSON,
} from './UserListResponseMeta';

/**
 * 
 * @export
 * @interface UserListResponse
 */
export interface UserListResponse {
    /**
     * 
     * @type {Array<UserData>}
     * @memberof UserListResponse
     */
    users: Array<UserData>;
    /**
     * 
     * @type {UserListResponseMeta}
     * @memberof UserListResponse
     */
    usersMeta: UserListResponseMeta;
    /**
     * 
     * @type {string}
     * @memberof UserListResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof UserListResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the UserListResponse interface.
 */
export function instanceOfUserListResponse(value: object): value is UserListResponse {
    if (!('users' in value) || value['users'] === undefined) return false;
    if (!('usersMeta' in value) || value['usersMeta'] === undefined) return false;
    return true;
}

export function UserListResponseFromJSON(json: any): UserListResponse {
    return UserListResponseFromJSONTyped(json, false);
}

export function UserListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'users': ((json['users'] as Array<any>).map(UserDataFromJSON)),
        'usersMeta': UserListResponseMetaFromJSON(json['usersMeta']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function UserListResponseToJSON(value?: UserListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'users': ((value['users'] as Array<any>).map(UserDataToJSON)),
        'usersMeta': UserListResponseMetaToJSON(value['usersMeta']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

