/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserSorting } from './UserSorting';
import {
    UserSortingFromJSON,
    UserSortingFromJSONTyped,
    UserSortingToJSON,
} from './UserSorting';

/**
 * 
 * @export
 * @interface UserListResponseMeta
 */
export interface UserListResponseMeta {
    /**
     * 
     * @type {string}
     * @memberof UserListResponseMeta
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserListResponseMeta
     */
    email?: string;
    /**
     * 
     * @type {UserSorting}
     * @memberof UserListResponseMeta
     */
    sort: UserSorting;
    /**
     * 
     * @type {boolean}
     * @memberof UserListResponseMeta
     */
    ascending?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UserListResponseMeta
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserListResponseMeta
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof UserListResponseMeta
     */
    totalCount?: number;
}

/**
 * Check if a given object implements the UserListResponseMeta interface.
 */
export function instanceOfUserListResponseMeta(value: object): value is UserListResponseMeta {
    if (!('sort' in value) || value['sort'] === undefined) return false;
    return true;
}

export function UserListResponseMetaFromJSON(json: any): UserListResponseMeta {
    return UserListResponseMetaFromJSONTyped(json, false);
}

export function UserListResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserListResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'sort': UserSortingFromJSON(json['sort']),
        'ascending': json['ascending'] == null ? undefined : json['ascending'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function UserListResponseMetaToJSON(value?: UserListResponseMeta | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'email': value['email'],
        'sort': UserSortingToJSON(value['sort']),
        'ascending': value['ascending'],
        'limit': value['limit'],
        'offset': value['offset'],
        'totalCount': value['totalCount'],
    };
}

