/* tslint:disable */
/* eslint-disable */
/**
 * metrics-sdk-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 5.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkersResponse
 */
export interface WorkersResponse {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WorkersResponse
     */
    workers: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof WorkersResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkersResponse
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the WorkersResponse interface.
 */
export function instanceOfWorkersResponse(value: object): value is WorkersResponse {
    if (!('workers' in value) || value['workers'] === undefined) return false;
    return true;
}

export function WorkersResponseFromJSON(json: any): WorkersResponse {
    return WorkersResponseFromJSONTyped(json, false);
}

export function WorkersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'workers': json['workers'],
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function WorkersResponseToJSON(value?: WorkersResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'workers': value['workers'],
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

